FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y gawk wget git-core diffstat unzip texinfo \
     build-essential chrpath socat cpio python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
     pylint xterm file

RUN mkdir -p /home/qset/yocto


WORKDIR /home/qset

# RUN git clone https://github.com/queens-satellite-team/yocto.git && true


COPY layers /home/qset/yocto/layers
COPY build/conf /home/qset/yocto/build/conf

WORKDIR /home/qset/yocto

CMD ["/bin/bash", "-c", ". /home/qset/yocto/layers/poky/oe-init-build-env && exec /bin/bash"]
